
POST http://localhost:3000/clients HTTP/1.1
Content-Type: application/json

{
    "name": "Jane Doe",
    "email": "jane@j.com"
}

###

POST http://localhost:3000/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "a8750f17-e8f9-4bbd-a6df-ea7694897ee4"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "8b253de7-99a5-491d-8f5c-9d1242155cdc",
    "account_id_to": "99b23063-6b7e-42b0-ba5b-9af20250881f",
    "amount": 5
}